新規投稿ページの作成
console-log-comp/sharm pull request #20
Opened 2021-12-14 04:50 UTC by alpaca1231

### 期待されること（できるだけ細かく編集・追加すること）

- [ ]  投稿に必要なデータの洗い出し
- [ ]  React hook form
- [ ]  Firebase Strage
- [ ]  改行も認識するようにする
- [ ]  投稿ボタン
- [ ]  過去に投稿があればホテル名などを選択できる
- [ ]  投稿する情報
    - [ ]  投稿者ID
    - [ ]  ホテル
    - [ ]  部屋
    - [ ]  画像
    - [ ]  評価
    - [ ]  価格
    - [ ]  コメント

【補足事項】

### UI（スクリーンショット）

### 懸念点

- 

### 最終確認事項

- [ ]  動作確認をしたか？
- [ ]  新たにエラーは発生していないか？
- [ ]  merge後に新たなタスクやIssueは発生するか？
- [ ]  これによる影響範囲を考え、それらに修正がある場合はそれをしたか？

### その他

-

2021-12-18 06:20 UTC, alpaca1231 reviewed
コメントしました。
レビューお願いします。

2021-12-18 06:20 UTC, alpaca1231 commented on src/App.jsx
> +import CreateHotelPage from 'pages/CreateHotel'
Componentフォルダから外に出しました。

2021-12-21 10:41 UTC, alpaca1231 reviewed
途中でコメントを書くのも面倒くさくなるくらい変更箇所多いです

2021-12-21 10:41 UTC, alpaca1231 commented on package.json
> +    "dayjs": "^1.10.7",
Day.js入れたけど結局使わなかった

2021-12-21 10:41 UTC, alpaca1231 commented on src/App.jsx
> +import CreateHotelPage from 'pages/CreateHotel'
pagesはcomponentsから出すことにしました！

2021-12-21 10:41 UTC, alpaca1231 commented on src/apis/firebase/hooks/post.js
> +        postImg.push(url)
複数枚の画像も順番にStorageへ保存しています

2021-12-21 10:41 UTC, alpaca1231 commented on src/apis/firebase/hooks/post.js
> +          atDate: serverTimestamp(),
まだ投稿されていないホテルに関してはhotelsに新規登録しています

2021-12-21 10:41 UTC, alpaca1231 commented on src/apis/firebase/hooks/post.js
> +        })
すでに登録されているホテルはpostIdの配列に追加する処理をしています

2021-12-21 10:41 UTC, alpaca1231 commented on src/components/commons/Button/index.jsx
> +        disabled={disabled}
ButtonComponentの仕様を変更しました
disabledを渡してtrueなら押し込まれた状態になります

2021-12-21 10:41 UTC, alpaca1231 commented on src/components/posts/PostForm.jsx
> +        </div>
デザインが足りなかったので一旦MUIのスライダーを置いてます。
やる気がある人にタスクをお渡しします

2021-12-21 12:45 UTC, ShoheiTakei approved these changes
動作確認もしてみましたが、動作に問題はなかったです！

2021-12-21 13:38 UTC, aspiratio requested changes
このままでも動くので大したことないですが一応指摘しました。

2021-12-21 13:38 UTC, aspiratio commented on src/apis/firebase/hooks/getPostData.js
> +    const postData = await querySnapshot.docs.map((doc) => doc.data())
この行のawaitは必要ないと思います。

2021-12-21 13:42 UTC, Koba-u-c approved these changes
PostFormの投稿条件を（hotelName＋写真）または（hotelName+コメント）が必須にした方がいいかなと思いました。

2021-12-21 13:47 UTC, alpaca1231 reviewed
修正しました

2021-12-21 13:47 UTC, alpaca1231 commented on src/apis/firebase/hooks/getPostData.js
> +    const postData = await querySnapshot.docs.map((doc) => doc.data())
```suggestion
    const postData =  querySnapshot.docs.map((doc) => doc.data())
```
消しちゃいました

2021-12-21 14:03 UTC, aspiratio approved these changes

2021-12-21 14:03 UTC, merged